# Generated by Django 5.1 on 2026-02-28 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admission_number", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")],
                        default="female",
                        max_length=10,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/"
                    ),
                ),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("birth_certificate_no", models.CharField(blank=True, max_length=30)),
                ("nemis_number", models.CharField(blank=True, max_length=30)),
                (
                    "kcpe_marks",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("kcpe_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("kcpe_index_number", models.CharField(blank=True, max_length=30)),
                ("admission_date", models.DateField()),
                (
                    "admission_type",
                    models.CharField(
                        choices=[
                            ("form1", "Form 1 (New)"),
                            ("transfer", "Transfer Student"),
                            ("repeat", "Repeat Student"),
                        ],
                        default="form1",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred Out"),
                            ("expelled", "Expelled"),
                            ("suspended", "Suspended"),
                            ("deceased", "Deceased"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_boarder", models.BooleanField(default=True)),
                ("dormitory", models.CharField(blank=True, max_length=100)),
                ("bed_number", models.CharField(blank=True, max_length=20)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("medical_conditions", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_students",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "current_stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.stream",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "unique_together": {("school", "admission_number")},
            },
        ),
        migrations.CreateModel(
            name="ParentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        default="guardian",
                        max_length=30,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="students.student"
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tsc_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("employee_number", models.CharField(blank=True, max_length=30)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Contract"),
                            ("bom", "BOM (Board of Management)"),
                            ("intern", "Teaching Practice"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deputy_principal", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("hod_department", models.CharField(blank=True, max_length=100)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="schools.school",
                    ),
                ),
                (
                    "specialization",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialist_teachers",
                        to="academics.subject",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentStreamHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_in_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.academicyear",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.stream",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__year"],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
