# Generated by Django 5.1 on 2026-02-28 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoCurricularActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("arts", "Music, Drama & Arts"),
                            ("academics", "Academic Clubs"),
                            ("community", "Community Service"),
                            ("religious", "Religious"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="activities/"),
                ),
                ("achievements", models.TextField(blank=True)),
                ("meeting_schedule", models.CharField(blank=True, max_length=200)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patronized_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academics", "Academics"),
                            ("sports", "Sports"),
                            ("culture", "Culture & Arts"),
                            ("trips", "Trips & Excursions"),
                            ("graduations", "Graduations & Awards"),
                            ("facilities", "Facilities"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/covers/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_albums",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/photos/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="website.galleryalbum",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="KCSEResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("total_candidates", models.PositiveSmallIntegerField(default=0)),
                ("candidates_sat", models.PositiveSmallIntegerField(default=0)),
                ("count_a_plain", models.PositiveSmallIntegerField(default=0)),
                ("count_a_minus", models.PositiveSmallIntegerField(default=0)),
                ("count_b_plus", models.PositiveSmallIntegerField(default=0)),
                ("count_b_plain", models.PositiveSmallIntegerField(default=0)),
                ("count_b_minus", models.PositiveSmallIntegerField(default=0)),
                ("count_c_plus", models.PositiveSmallIntegerField(default=0)),
                ("count_c_plain", models.PositiveSmallIntegerField(default=0)),
                ("count_c_minus", models.PositiveSmallIntegerField(default=0)),
                ("count_d_plus", models.PositiveSmallIntegerField(default=0)),
                ("count_d_plain", models.PositiveSmallIntegerField(default=0)),
                ("count_d_minus", models.PositiveSmallIntegerField(default=0)),
                ("count_e", models.PositiveSmallIntegerField(default=0)),
                ("mean_grade", models.CharField(blank=True, max_length=3)),
                (
                    "mean_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "county_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "national_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("university_qualifiers", models.PositiveSmallIntegerField(default=0)),
                ("top_student_name", models.CharField(blank=True, max_length=200)),
                (
                    "top_student_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("top_student_grade", models.CharField(blank=True, max_length=3)),
                ("summary", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kcse_results",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("school", "year")},
            },
        ),
        migrations.CreateModel(
            name="NewsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320)),
                ("content", models.TextField()),
                ("summary", models.CharField(blank=True, max_length=500)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="news/"),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("event", "Event"),
                            ("notice", "Notice"),
                        ],
                        default="news",
                        max_length=10,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_location", models.CharField(blank=True, max_length=200)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_events",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("school", "slug")},
            },
        ),
    ]
