# Generated by Django 5.1 on 2026-02-28 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("cat1", "CAT 1"),
                            ("cat2", "CAT 2"),
                            ("midterm", "Mid-Term"),
                            ("endterm", "End of Term"),
                            ("mock", "Mock KCSE"),
                            ("kcse", "KCSE (National Exam)"),
                            ("other", "Other"),
                        ],
                        default="endterm",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_kcse", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.school",
                    ),
                ),
                (
                    "streams",
                    models.ManyToManyField(
                        blank=True, related_name="exams", to="academics.stream"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__year", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A (80-100)"),
                            ("A-", "A- (75-79)"),
                            ("B+", "B+ (70-74)"),
                            ("B", "B (65-69)"),
                            ("B-", "B- (60-64)"),
                            ("C+", "C+ (55-59)"),
                            ("C", "C (50-54)"),
                            ("C-", "C- (45-49)"),
                            ("D+", "D+ (40-44)"),
                            ("D", "D (35-39)"),
                            ("D-", "D- (30-34)"),
                            ("E", "E (0-29)"),
                            ("X", "X - Absent"),
                            ("Y", "Y - Cancelled"),
                        ],
                        max_length=3,
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_absent", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("teacher_remarks", models.CharField(blank=True, max_length=300)),
                (
                    "stream_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "school_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student", "subject")},
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "total_points",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "mean_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A (80-100)"),
                            ("A-", "A- (75-79)"),
                            ("B+", "B+ (70-74)"),
                            ("B", "B (65-69)"),
                            ("B-", "B- (60-64)"),
                            ("C+", "C+ (55-59)"),
                            ("C", "C (50-54)"),
                            ("C-", "C- (45-49)"),
                            ("D+", "D+ (40-44)"),
                            ("D", "D (35-39)"),
                            ("D-", "D- (30-34)"),
                            ("E", "E (0-29)"),
                            ("X", "X - Absent"),
                            ("Y", "Y - Cancelled"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "mean_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("subjects_sat", models.PositiveSmallIntegerField(default=0)),
                (
                    "stream_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "stream_size",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "school_position",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "school_size",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("class_teacher_remarks", models.TextField(blank=True)),
                ("principal_remarks", models.TextField(blank=True)),
                (
                    "fee_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="report_cards/"),
                ),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="exams.exam",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.stream",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "exam")},
            },
        ),
    ]
