# Generated by Django 5.1 on 2026-03-05 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("1", "Period 1 (7:00 - 7:40)"),
                            ("2", "Period 2 (7:40 - 8:20)"),
                            ("3", "Period 3 (8:20 - 9:00)"),
                            ("4", "Period 4 (9:00 - 9:40)"),
                            ("5", "Break (9:40 - 10:00)"),
                            ("6", "Period 5 (10:00 - 10:40)"),
                            ("7", "Period 6 (10:40 - 11:20)"),
                            ("8", "Period 7 (11:20 - 12:00)"),
                            ("9", "Lunch (12:00 - 1:00)"),
                            ("10", "Period 8 (1:00 - 1:40)"),
                            ("11", "Period 9 (1:40 - 2:20)"),
                            ("12", "Period 10 (2:20 - 3:00)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("is_break", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="schools.school",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="academics.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "period"],
                "unique_together": {("stream", "academic_year", "day", "period")},
            },
        ),
    ]
