# Generated by Django 5.1 on 2026-02-28 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("motto", models.CharField(blank=True, max_length=300)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/"
                    ),
                ),
                ("address", models.TextField()),
                ("county", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("po_box", models.CharField(blank=True, max_length=50)),
                ("knec_code", models.CharField(blank=True, max_length=20)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("boarding", "Boarding"),
                            ("day", "Day"),
                            ("mixed", "Day & Boarding"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "gender_type",
                    models.CharField(
                        choices=[
                            ("girls", "Girls"),
                            ("boys", "Boys"),
                            ("mixed", "Mixed"),
                        ],
                        default="girls",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("extra_county", "Extra County"),
                            ("county", "County"),
                            ("sub_county", "Sub County"),
                        ],
                        default="county",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("trial", "Free Trial"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("subscription_expires", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "current_term",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("school", "year")},
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")]
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="schools.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("academic_year", "number")},
            },
        ),
    ]
